//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAvailableDeliveryStaff
    {
        public int Id { get; set; }
        public int DeliveryStaffId { get; set; }
        public bool Available { get; set; }
        public Nullable<System.DateTime> NextAvailableTime { get; set; }
        public int MaxOrders { get; set; }
    }
}
