//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppUser
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<System.DateTime> LogoutDate { get; set; }
        public Nullable<int> TotalDrinks { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string DeviceID { get; set; }
        public string Token { get; set; }
        public string DeviceType { get; set; }
        public Nullable<bool> WebUpload { get; set; }
    }
}
