//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerFeedback
    {
        public int FeedbackId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Mobile { get; set; }
        public decimal OverallRating { get; set; }
        public string Recommendation { get; set; }
        public string Feedback { get; set; }
        public string OrderNo { get; set; }
        public string OrderType { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
