//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerActivity
    {
        public int ActivityId { get; set; }
        public int CustomerId { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int RewardPoints { get; set; }
        public int RedeemPoints { get; set; }
        public bool Paid { get; set; }
        public bool WebUpload { get; set; }
        public string ActivityType { get; set; }
        public string FullName { get; set; }
    }
}
