//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDrinksTarget
    {
        public int ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string PCName { get; set; }
        public int UserID { get; set; }
        public string TargetName { get; set; }
        public string TargetDate { get; set; }
        public int ProductID { get; set; }
        public int ProductTarget { get; set; }
        public int Count { get; set; }
        public Nullable<bool> WebUpload { get; set; }
        public Nullable<int> ProductTypeTargetID { get; set; }
    }
}
