//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeliveryPostCode
    {
        public int Id { get; set; }
        public string PostCode { get; set; }
        public bool Delivery { get; set; }
        public bool DelInd { get; set; }
        public Nullable<int> PostCodePriority { get; set; }
    }
}
