//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbliPodLog
    {
        public long iPodLogID { get; set; }
        public string vMessage { get; set; }
        public string vFunction { get; set; }
        public string vPage { get; set; }
        public Nullable<int> iUserID { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
    }
}
