//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJoinedTable
    {
        public int JoinedTablesId { get; set; }
        public System.Guid OrderGuid { get; set; }
        public int TableId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public Nullable<int> ReleasedBy { get; set; }
        public bool Released { get; set; }
    }
}
