//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public string MenuName { get; set; }
        public string MenuDescription { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool DelInd { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public int MenuID { get; set; }
        public string ImageName { get; set; }
        public bool FixedProducts { get; set; }
    }
}
