//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNote
    {
        public int NoteID { get; set; }
        public string NoteText { get; set; }
        public System.DateTime NoteLiveDate { get; set; }
        public System.DateTime NoteEndDate { get; set; }
        public bool DelInd { get; set; }
    }
}
