//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderPart
    {
        public int OrderPartID { get; set; }
        public int ProductID { get; set; }
        public Nullable<short> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Total { get; set; }
        public bool DelInd { get; set; }
        public System.Guid OrderGUID { get; set; }
        public long UserID { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<int> OldOrderPartID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateServed { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<bool> WebUpload { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public bool Paid { get; set; }
        public int BatchNo { get; set; }
        public string Mobile { get; set; }
        public string UserName { get; set; }
        public string VendorTxCode { get; set; }
        public bool Locked { get; set; }
    }
}
