//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderAdjustmentAfterBill
    {
        public int AdjustmentID { get; set; }
        public int ProductFK { get; set; }
        public int UserFK { get; set; }
        public bool Removed { get; set; }
        public bool Added { get; set; }
        public string PCName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
    }
}
