//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderVoucher
    {
        public int OrderVoucherId { get; set; }
        public System.Guid OrderGUID { get; set; }
        public string VoucherNumber { get; set; }
        public string VoucherValue { get; set; }
        public string VoucherType { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<decimal> PartAmount { get; set; }
        public bool DelInd { get; set; }
        public Nullable<decimal> VoucherAmount { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> StopPromotion { get; set; }
    }
}
