//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderPartDelete
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public Nullable<short> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Total { get; set; }
        public bool DelInd { get; set; }
        public System.Guid OrderGUID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> OrderPartID { get; set; }
        public Nullable<bool> BillPrinted { get; set; }
        public Nullable<bool> TableDel { get; set; }
        public Nullable<bool> WebUpload { get; set; }
    }
}
