//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderPayment
    {
        public System.Guid PaymentGUID { get; set; }
        public System.Guid OrderGUID { get; set; }
        public string PaymentType { get; set; }
        public decimal PaymentValue { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string PCName { get; set; }
        public decimal Change { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<decimal> TipAmount { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public string PGName { get; set; }
    }
}
