//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrintBuffetItem
    {
        public int Id { get; set; }
        public int TableId { get; set; }
        public System.Guid OrderGUID { get; set; }
        public int ProductId { get; set; }
        public int Qty { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Printed { get; set; }
        public Nullable<System.DateTime> DateServed { get; set; }
        public Nullable<long> UserId { get; set; }
        public string UserType { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> WebUpload { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public int BatchNo { get; set; }
        public string BatchTime { get; set; }
        public bool Processed { get; set; }
        public bool ReOrder { get; set; }
        public bool Delivered { get; set; }
        public Nullable<bool> DirectPrint { get; set; }
        public Nullable<int> MenuId { get; set; }
        public bool InProcess { get; set; }
    }
}
