//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductRefillTemplatesItem
    {
        public int iRefillTemplateItemID { get; set; }
        public int RefillTemplateFK { get; set; }
        public int ProductFK { get; set; }
        public bool SmallPortion { get; set; }
        public bool RegularPortion { get; set; }
        public bool LargePortion { get; set; }
        public string Options { get; set; }
        public bool DelInd { get; set; }
        public Nullable<int> ProductQty { get; set; }
    }
}
