//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductTimeRestriction
    {
        public int RestrictionID { get; set; }
        public int ProductID { get; set; }
        public int DayID { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public bool DelInd { get; set; }
    }
}
