//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductWastage
    {
        public int WastageID { get; set; }
        public System.DateTime Date { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
