//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrintQueue
    {
        public int PrintQueueID { get; set; }
        public int UserFK { get; set; }
        public string PCName { get; set; }
        public string ToPrinter { get; set; }
        public string Receipt { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public bool Processed { get; set; }
        public int ProcessedBy { get; set; }
        public int BatchNo { get; set; }
        public string TableNumber { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public int OldBatchNo { get; set; }
        public string TicketNo { get; set; }
        public int TicketStatus { get; set; }
    }
}
