//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReservation
    {
        public int ReservationID { get; set; }
        public string Tables { get; set; }
        public string ReservationUnder { get; set; }
        public int ReservationTime { get; set; }
        public string ContactNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public bool Delind { get; set; }
        public string ReservationNotes { get; set; }
        public short NoOfGuests { get; set; }
        public bool OnlineReservation { get; set; }
        public Nullable<bool> bDepositPaid { get; set; }
        public string ForeName { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<bool> C2P { get; set; }
        public Nullable<decimal> C2Pvalue { get; set; }
        public Nullable<int> NoOfSeats { get; set; }
        public Nullable<int> NoOfHighChairs { get; set; }
        public Nullable<int> NoOfWheelChairs { get; set; }
        public Nullable<int> NoOfPrams { get; set; }
        public Nullable<System.DateTime> LastContacted { get; set; }
        public Nullable<System.Guid> ProcessedOrderGUID { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string EmailID { get; set; }
        public string DOB { get; set; }
        public Nullable<int> AdCount { get; set; }
        public Nullable<int> KdCount { get; set; }
        public Nullable<int> JnCount { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ReservationType { get; set; }
        public Nullable<bool> TelReservation { get; set; }
        public Nullable<bool> SMSDepPaid { get; set; }
        public Nullable<int> Deposit { get; set; }
        public string UniqueCode { get; set; }
        public Nullable<bool> UniqueCodeUsed { get; set; }
        public Nullable<bool> WebUpload { get; set; }
        public Nullable<int> AdminReservationId { get; set; }
        public bool InLounge { get; set; }
        public int RestaurantId { get; set; }
    }
}
