//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReservationName
    {
        public int ReservationNameID { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string ContactNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Delind { get; set; }
    }
}
