//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequestBilliPod
    {
        public long iRequestBillID { get; set; }
        public Nullable<System.DateTime> dtDateTimeCreated { get; set; }
        public Nullable<int> iTableID { get; set; }
        public Nullable<bool> bPrinted { get; set; }
        public Nullable<System.DateTime> dtDateTimePrinted { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
    }
}
