//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecordPayment
    {
        public int RecordPaymentId { get; set; }

        public System.Guid OrderGUID { get; set; }

        public long MobileNumber { get; set; }

        public string CustomerName { get; set; }

        public string ScreenshotType { get; set; }

        public decimal TotalAmt { get; set; }

        public Nullable<System.DateTime> DateCreated { get; set; }

        public Nullable<bool> DelInd { get; set; }

        public string VendorTXCode { get; set; }

        public int RestaurantFK { get; set; }

        public string Base64Image { get; set; }

    }
}
