//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesRecording
    {
        public int ID { get; set; }
        public int BranchID { get; set; }
        public string PCName { get; set; }
        public string CashierName { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Date { get; set; }
        public Nullable<int> UserID { get; set; }
        public decimal CashSales { get; set; }
        public decimal CardSales { get; set; }
        public decimal ChequeSales { get; set; }
        public decimal PDQSales { get; set; }
        public decimal PDQTips { get; set; }
        public decimal AmexSales { get; set; }
        public decimal AmexTips { get; set; }
        public Nullable<decimal> CalculatedCash { get; set; }
        public Nullable<decimal> AttemptedCash { get; set; }
        public Nullable<decimal> AcceptedCash { get; set; }
        public Nullable<decimal> ConfirmedCash { get; set; }
        public Nullable<bool> HQSubmit { get; set; }
        public Nullable<bool> Hide { get; set; }
        public Nullable<decimal> Cash5 { get; set; }
        public Nullable<decimal> Cash20 { get; set; }
        public Nullable<decimal> Card5 { get; set; }
        public Nullable<decimal> Card20 { get; set; }
        public Nullable<decimal> MP5 { get; set; }
        public Nullable<decimal> MP20 { get; set; }
        public Nullable<decimal> MPTips { get; set; }
        public Nullable<decimal> CardServiceCharge { get; set; }
        public Nullable<decimal> MPServiceCharge { get; set; }
        public Nullable<decimal> CashServiceCharge { get; set; }
        public Nullable<bool> WebUpload { get; set; }
    }
}
