//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierOrderItem
    {
        public int SupplierOrderItemId { get; set; }
        public int PurchaseOrderNumberFK { get; set; }
        public int ProductFK { get; set; }
        public string ProductName { get; set; }
        public decimal Quantity { get; set; }
        public decimal Received { get; set; }
        public bool Cancelled { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public bool PoorQuality { get; set; }
        public bool QuantityUnder { get; set; }
        public bool QuantityOver { get; set; }
        public bool TemperatureIssue { get; set; }
        public bool ExpirationIssue { get; set; }
        public bool Return { get; set; }
        public Nullable<bool> Checked { get; set; }
        public decimal SupplierAmount { get; set; }
    }
}
