//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStripePayment
    {
        public int Id { get; set; }
        public System.Guid OrderGUID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ClientSecret { get; set; }
        public bool Success { get; set; }
        public string FailureMessage { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public decimal Amount { get; set; }
        public string PaymentId { get; set; }
        public string VendorTxCode { get; set; }
        public string DeviceType { get; set; }
        public string MobileNo { get; set; }
        public bool SplitPayment { get; set; }
        public Nullable<double> PaymentPrice { get; set; }
        public int TipAmount { get; set; }
        public double SCAmount { get; set; }
    }
}
