//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSagePayment
    {
        public int PaymentID { get; set; }
        public System.Guid OrderID { get; set; }
        public string TransactionID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> StatusUpdated { get; set; }
        public Nullable<double> PaymentPrice { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string FaultReason { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string SecurityKey { get; set; }
        public string VendorTXCode { get; set; }
        public string DeviceType { get; set; }
        public string MobileNo { get; set; }
        public bool SplitPayment { get; set; }
        public int TipAmount { get; set; }
        public double SCAmount { get; set; }
    }
}
