//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierOrder
    {
        public int SupplierOrderId { get; set; }
        public int PurchaseOrderNumber { get; set; }
        public string Supplier { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool Completed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Authorizer { get; set; }
        public string Frozen { get; set; }
        public string Chill { get; set; }
        public string Condition { get; set; }
        public string Quantity { get; set; }
        public string SupplierSign { get; set; }
        public string AuthorizerSign { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool DelInd { get; set; }
        public bool UrgentReport { get; set; }
        public bool WebUpload { get; set; }
        public Nullable<bool> Saved { get; set; }
        public Nullable<int> StaffUserCode { get; set; }
        public Nullable<int> ManagerUserCode { get; set; }
        public decimal SupplierTotalAmount { get; set; }
        public int SupplierFK { get; set; }
    }
}
