//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStockOrder()
        {
            this.tblStockOrderProducts = new HashSet<tblStockOrderProduct>();
        }
    
        public int PurchaseOrderNumber { get; set; }
        public int UserId { get; set; }
        public int iTemplateID { get; set; }
        public string TemplateName { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Processed { get; set; }
        public bool Completed { get; set; }
        public bool DelInd { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public Nullable<System.DateTime> RequiredBy { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> OldPONumber { get; set; }
        public bool WebUpload { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockOrderProduct> tblStockOrderProducts { get; set; }
    }
}
