//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierOrderImage
    {
        public int ImageId { get; set; }
        public int SupplierOrderid { get; set; }
        public int PurchaseOrderNumberFK { get; set; }
        public string Image { get; set; }
        public Nullable<bool> DelInd { get; set; }
    }
}
