//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTakeAwayOrder
    {
        public int TakeAwayId { get; set; }
        public int AddressID { get; set; }
        public string NAME { get; set; }
        public int CollectionTime { get; set; }
        public string Phone { get; set; }
        public int HasPrinted { get; set; }
        public int HasBeenCollected { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public int delInd { get; set; }
        public System.DateTime LastModified { get; set; }
        public string PaymentType { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<bool> bTakeaway { get; set; }
        public Nullable<bool> bDelivery { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> HasBeenPrepared { get; set; }
        public Nullable<int> HasBeenDelivered { get; set; }
        public bool bOffline { get; set; }
        public bool WebUpload { get; set; }
    }
}
