//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTable
    {
        public int TableID { get; set; }
        public string TableNumber { get; set; }
        public bool DelInd { get; set; }
        public int SortOrder { get; set; }
        public int CurrentStatus { get; set; }
        public int Top { get; set; }
        public int Left { get; set; }
        public string OccupiedTime { get; set; }
        public string EditingOnTill { get; set; }
        public int PrinterFK { get; set; }
        public Nullable<int> PastStatus { get; set; }
        public Nullable<int> SectionId { get; set; }
    }
}
