//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTakeAwayOrderDelivery
    {
        public int Id { get; set; }
        public int TakeAwayId { get; set; }
        public System.Guid OrderGUID { get; set; }
        public Nullable<int> DeliveryStaffId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CollectedAt { get; set; }
        public Nullable<System.DateTime> DeliveredAt { get; set; }
        public bool DelInd { get; set; }
        public Nullable<decimal> AmountCollected { get; set; }
        public Nullable<int> CollectedBy { get; set; }
        public Nullable<System.DateTime> AmountCollectedAt { get; set; }
    }
}
