//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTablesCleaning
    {
        public int ID { get; set; }
        public int TableID { get; set; }
        public System.DateTime BillingTime { get; set; }
        public System.Guid OrderGUID { get; set; }
        public Nullable<System.DateTime> AvailableTime { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
