//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTillPromotion
    {
        public int PromotionId { get; set; }
        public int PromoId { get; set; }
        public string Promotion { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool DelInd { get; set; }
        public string PromoCode { get; set; }
        public string Description { get; set; }
        public string VoucherValue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int MaxVouchers { get; set; }
        public bool TillPromotion { get; set; }
        public bool Archived { get; set; }
    }
}
