//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTableOrder
    {
        public int Id { get; set; }
        public int TableId { get; set; }
        public System.Guid OrderGUID { get; set; }
        public int CustomerCount { get; set; }
        public int UniqueCode { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateValidated { get; set; }
        public Nullable<System.DateTime> NextOrderTime { get; set; }
        public Nullable<int> SignInCount { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> QRCodePrint { get; set; }
        public Nullable<bool> BarCodePrint { get; set; }
    }
}
