//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserSwipeHistory
    {
        public int SwipeID { get; set; }
        public int UserFK { get; set; }
        public string TillName { get; set; }
        public string ScanCode { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
