//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZCashSale
    {
        public int ZID { get; set; }
        public string PCName { get; set; }
        public System.DateTime ZDate { get; set; }
        public int UserID { get; set; }
        public int Fiftypound { get; set; }
        public int Twentypound { get; set; }
        public int Tenpound { get; set; }
        public int Fivepound { get; set; }
        public int Twopound { get; set; }
        public int Onepound { get; set; }
        public int Fiftypence { get; set; }
        public int Twentypence { get; set; }
        public int Tenpence { get; set; }
        public int Fivepence { get; set; }
        public int Twopence { get; set; }
        public int Onepence { get; set; }
        public decimal CashTotal { get; set; }
        public decimal TillCashSale { get; set; }
        public decimal Difference { get; set; }
    }
}
