//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAllIndex
    {
        public string TABLE_NAME { get; set; }
        public string INDEX_NAME { get; set; }
        public string COLUMN_LIST { get; set; }
        public Nullable<int> IS_CLUSTERED { get; set; }
        public Nullable<int> IS_UNIQUE { get; set; }
        public string FILE_GROUP { get; set; }
    }
}
