//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwANTableStatus1
    {
        public int TableID { get; set; }
        public int CurrentStatus { get; set; }
        public int Top { get; set; }
        public int Left { get; set; }
        public string OccupiedTime { get; set; }
        public int UniqueCode { get; set; }
        public Nullable<decimal> CurrentTotal { get; set; }
        public Nullable<int> AdCount { get; set; }
        public Nullable<int> KdCount { get; set; }
        public Nullable<int> JnCount { get; set; }
        public bool ServiceRequired { get; set; }
        public string TableNumber { get; set; }
    }
}
