//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwANProduct
    {
        public Nullable<int> ProductGroupID { get; set; }
        public string Groupname { get; set; }
        public Nullable<int> ParentGroupID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<bool> CustomisePrice { get; set; }
        public Nullable<bool> ProductAvailable { get; set; }
        public int HasLinkedProducts { get; set; }
    }
}
