//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProductsOptionsOnOrderTemp
    {
        public string Description { get; set; }
        public int TableID { get; set; }
        public bool bComitted { get; set; }
        public int OrderPartId { get; set; }
    }
}
