//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBROMS_Android_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReservation
    {
        public int ReservationID { get; set; }
        public string Reservation { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public int ReservationTime { get; set; }
        public string ReservationNotes { get; set; }
        public short NoOfGuests { get; set; }
        public string Tables { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public bool OnLineReservation { get; set; }
        public Nullable<bool> bDepositPaid { get; set; }
        public Nullable<bool> Processed { get; set; }
    }
}
